#To develop make sure to activate the development spring profile (-Dspring.profiles.active=development)
spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1/wicket?autoReconnect=true&useSSL=false"
    username: "root"
    password: "wicket"
